import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const DICTIONARY: Record<string, Record<Language, string>> = {
  appName: { en: 'SHOHAY', bn: 'সহায়' },
  subTitle: { en: 'Bangladesh Flood Relief Platform', bn: 'বাংলাদেশ বন্যা সহায়তা প্ল্যাটফর্ম' },
  home: { en: 'Home', bn: 'হোম' },
  alerts: { en: 'Alerts', bn: 'সতর্কতা' },
  shelters: { en: 'Shelters', bn: 'আশ্রয়কেন্দ্র' },
  getHelp: { en: 'Get Help', bn: 'সাহায্য নিন' },
  campaigns: { en: 'Campaigns', bn: 'ক্যাম্পেইন' },
  contacts: { en: 'Contacts', bn: 'যোগাযোগ' },
  signIn: { en: 'Sign In', bn: 'সাইন ইন' },
  signOut: { en: 'Sign Out', bn: 'সাইন আউট' },
  exit: { en: 'Exit', bn: 'বাহির' },
  volunteer: { en: 'Volunteer', bn: 'স্বেচ্ছাসেবক' },
  admin: { en: 'Command Center', bn: 'কমান্ড সেন্টার' },
  fieldDashboard: { en: 'Field Dashboard', bn: 'ফিল্ড ড্যাশবোর্ড' },
  banglaBtn: { en: 'বাং', bn: 'EN' },
  signedInAs: { en: 'Signed in as', bn: 'লগইন আছেন' },
  // Footer
  footerDesc: { en: 'Coordinating immediate rescue, shelter, and relief operations for flood-affected communities.', bn: 'বন্যা কবলিত সম্প্রদায়ের জন্য তাৎক্ষণিক উদ্ধার, আশ্রয় ও ত্রাণ কার্যক্রম সমন্বয় করা হচ্ছে।' },
  publicServices: { en: 'Public Services', bn: 'জনসেবা' },
  floodAlerts: { en: 'Flood Alerts', bn: 'বন্যা সতর্কতা' },
  findShelter: { en: 'Find Shelter', bn: 'আশ্রয় খুঁজুন' },
  requestAssistance: { en: 'Request Assistance', bn: 'সাহায্যের আবেদন' },
  reportHazard: { en: 'Report Hazard', bn: 'দুর্যোগ রিপোর্ট করুন' },
  emergencyContacts: { en: 'Emergency Contacts', bn: 'জরুরি যোগাযোগ' },
  platformHeading: { en: 'Platform', bn: 'প্ল্যাটফর্ম' },
  trackRequest: { en: 'Track Request', bn: 'আবেদন ট্র্যাক করুন' },
  campaignsDonations: { en: 'Campaigns & Donations', bn: 'ক্যাম্পেইন ও অনুদান' },
  feedback: { en: 'Feedback', bn: 'মতামত' },
  staffLogin: { en: 'Staff Login', bn: 'স্টাফ লগইন' },
  footerDisclaimer1: { en: 'SHOHAY / সহায় — Prototype Platform for Bangladesh Flood Relief Coordination', bn: 'সহায় — বাংলাদেশ বন্যা ত্রাণ সমন্বয় প্রোটোটাইপ প্ল্যাটফর্ম' },
  footerDisclaimer2: { en: 'All data shown is placeholder content for demonstration purposes', bn: 'প্রদর্শিত সমস্ত তথ্য প্রদর্শনের উদ্দেশ্যে সংরক্ষিত ডেমো তথ্য' },
  // Home Page
  homeAlertLabel: { en: 'Critical Alert — Immediate Action Required', bn: 'জরুরি সতর্কতা — অবিলম্বে পদক্ষেপ নিন' },
  homeAlertTitle: { en: 'Extreme Flash Flood Warning — Sunamganj Sadar', bn: 'মারাত্মক আকস্মিক বন্যা সতর্কতা — সুনামগঞ্জ সদর' },
  homeAlertAreas: { en: 'Sunamganj Sadar, Bishwambarpur, Tahirpur, Derai', bn: 'সুনামগঞ্জ সদর, বিশ্বম্ভরপুর, তাহিরপুর, দিরাই' },
  homeViewAlert: { en: 'View Alert', bn: 'সতর্কতা দেখুন' },
  homeGetHelpNow: { en: 'Get Help Now', bn: 'জরুরি সাহায্য নিন' },
  homeSetLocation: { en: 'Set Location:', bn: 'স্থান নির্ধারণ:' },
  homeGps: { en: 'GPS', bn: 'জিপিএস' },
  homeSelectUpazila: { en: 'Select Upazila...', bn: 'উপজেলা নির্বাচন করুন...' },
  homeSkip: { en: 'Skip', bn: 'এড়িয়ে যান' },
  homeStatReached: { en: 'Reached', bn: 'সাহায্যপ্রাপ্ত' },
  homeStatShelters: { en: 'Shelters', bn: 'আশ্রয়কেন্দ্র' },
  homeStatPackages: { en: 'Packages', bn: 'ত্রাণ সামগ্রী' },
  homeStatRescues: { en: 'Rescues', bn: 'উদ্ধারকৃত' },
  homeWaterRisk: { en: 'Water Risk', bn: 'পানির বিপদসীমা' },
  homeLiveTicker: { 
    en: '🔴 LIVE — Sunamganj: Water level 3.2m above danger level · Brahmaputra rising at 5cm/hr · 14 upazilas on red alert · Evacuations ongoing in Bishwambarpur · BNCC deploying additional rescue boats',
    bn: '🔴 সরাসরি — সুনামগঞ্জ: পানি বিপদসীমার ৩.২ মিটার উপরে · ব্রহ্মপুত্রের পানি প্রতি ঘণ্টায় ৫ সেমি বৃদ্ধি পাচ্ছে · ১৪টি উপজেলায় লাল সতর্কতা · বিশ্বম্ভরপুরে স্থানান্তর কার্যক্রম চলমান · বিএনসিসি অতিরিক্ত উদ্ধারকারী নৌকা মোতায়েন করেছে'
  },
  homeHeroBadge: { en: 'Emergency Response · Bangladesh', bn: 'জরুরি সাড়াদান · বাংলাদেশ' },
  homeHeroTitle: { en: 'Standing With Bangladesh in Times of Crisis.', bn: 'সংকটময় মুহূর্তে বাংলাদেশের পাশে।' },
  homeHeroDesc: { en: 'Coordinating immediate rescue, shelter access, and transparent relief tracking for flood-affected communities across Bangladesh.', bn: 'বাংলাদেশ জুড়ে বন্যা কবলিত সম্প্রদায়ের জন্য তাৎক্ষণিক উদ্ধার, নিরাপদ আশ্রয় এবং স্বচ্ছ ত্রাণ পর্যবেক্ষণ সমন্বয় করা হচ্ছে।' },
  homeHeroRequestAssistance: { en: 'Request Assistance', bn: 'সাহায্যের আবেদন' },
  homeHeroDonate: { en: 'Donate', bn: 'অনুদান দিন' },
  homeHeroScroll: { en: 'Scroll', bn: 'স্ক্রোল করুন' },
  homeMissionTag: { en: 'Our Mission', bn: 'আমাদের লক্ষ্য' },
  homeMissionHeading: { en: 'We coordinate with communities impacted by floods to save lives, restore dignity, and rebuild resilience across Bangladesh.', bn: 'জীবন বাঁচাতে, মর্যাদা রক্ষা করতে এবং দুর্যোগ কাটিয়ে উঠতে আমরা বন্যা দুর্গত মানুষের পাশে কাজ করছি।' },
  homeLearnMore: { en: 'Learn More', bn: 'আরও জানুন' },
  homeMissionStat1Label: { en: 'people served in 2024', bn: '২০২৪ সালে সেবা প্রাপ্ত নাগরিক' },
  homeMissionStat2Label: { en: 'partner orgs nationwide', bn: 'সারাদেশে সহযোগী সংস্থা' },
  homeMissionStat3Label: { en: 'led by local staff', bn: 'স্থানীয় স্বেচ্ছাসেবক পরিচালিত' },
  homeRescueOpsBadge: { en: 'Rescue Ops', bn: 'উদ্ধার অভিযান' },
  homeRescueOpsSub: { en: 'coordinated rescues · 2024', bn: 'সমন্বিত উদ্ধার · ২০২৪' },
  homeFindShelterTitle: { en: 'Find Shelter', bn: 'আশ্রয় খুঁজুন' },
  homeFindShelterDesc: { en: 'Real-time capacity at safe havens near you', bn: 'নিকটস্থ আশ্রয়কেন্দ্রে বর্তমান খালি আসনের তথ্য' },
  homeReportHazardTitle: { en: 'Report Hazard', bn: 'দুর্যোগ রিপোর্ট করুন' },
  homeReportHazardDesc: { en: 'Anonymously flag flooded roads or dangers', bn: 'প্লাবিত রাস্তা বা বিপদের তথ্য নিরাপদে জানান' },
  homeRequestHelpTitle: { en: 'Request Help', bn: 'সাহায্য চান' },
  homeRequestHelpDesc: { en: 'Submit rescue or relief assistance requests', bn: 'উদ্ধার বা ত্রাণ সহায়তার জন্য আবেদন করুন' },
  homeEmergencyLinesTitle: { en: 'Emergency Lines', bn: 'জরুরি হটলাইন' },
  homeEmergencyLinesDesc: { en: 'Direct lines to rescue and medical services', bn: 'উদ্ধার ও চিকিৎসা সেবার সরাসরি নম্বর' },
  homeLiveSituationTitle: { en: 'Live Situation · Bangladesh Floods 2024', bn: 'বর্তমান পরিস্থিতি · বাংলাদেশ বন্যা ২০২৪' },
  homePeopleAffected: { en: 'People Affected', bn: 'ক্ষতিগ্রস্ত মানুষ' },
  homeAcrossDistricts: { en: 'across 18 districts', bn: '১৮টি জেলা জুড়ে' },
  homeHomesDamaged: { en: 'Homes Damaged', bn: 'ক্ষতিগ্রস্ত ঘরবাড়ি' },
  homeFullPartialDamage: { en: 'full or partial damage', bn: 'সম্পূর্ণ বা আংশিক ক্ষতি' },
  homeKmSubmerged: { en: 'km² Submerged', bn: 'বর্গকিমি প্লাবিত' },
  homeCroplandsInundated: { en: 'croplands inundated', bn: 'ফসলি জমি জলমগ্ন' },
  homeRescueBoatsActive: { en: 'Rescue Boats Active', bn: 'সক্রিয় উদ্ধারকারী নৌকা' },
  homeBnccArmyDeployed: { en: 'BNCC + Army deployed', bn: 'বিএনসিসি ও সেনা মোতায়েন' },
  homeNewsTag: { en: 'Our Work Across Bangladesh', bn: 'সারা বাংলাদেশে আমাদের কার্যক্রম' },
  homeNewsTitle: { en: 'News and Stories', bn: 'সংবাদ ও বিশেষ প্রতিবেদন' },
  homeReadMore: { en: 'Read More', bn: 'বিস্তারিত পড়ুন' },
  homeRead: { en: 'Read', bn: 'পড়ুন' },
  homeFieldReport: { en: 'FIELD REPORT', bn: 'মাঠপর্যায় রিপোর্ট' },
  homeRescueCat: { en: 'RESCUE', bn: 'উদ্ধার' },
  homeFeaturedNewsTitle: { en: 'Over 12,000 families evacuated as floodwaters breach Sunamganj embankments', bn: 'সুনামগঞ্জে বাঁধ ভেঙে প্লাবিত এলাকা থেকে ১২,০০০-এর বেশি পরিবারকে নিরাপদে স্থানান্তর' },
  homeFeaturedNewsExcerpt: { en: 'Coordinated rescue boats deployed across 14 upazilas to move stranded families to safety.', bn: 'আটকে পড়া পরিবারগুলোকে নিরাপদে সরিয়ে নিতে ১৪টি উপজেলায় সমন্বিত উদ্ধার নৌকা মোতায়েন করা হয়েছে।' },
  homeHealthCat: { en: 'HEALTH', bn: 'স্বাস্থ্য' },
  homeNews2Title: { en: 'Mobile medical units reach flood-isolated char communities in Sirajganj', bn: 'সিরাজগঞ্জের দুর্গম চরে চিকিৎসা সেবা পৌঁছে দিচ্ছে ভ্রাম্যমাণ মেডিকেল টিম' },
  homeCommunityCat: { en: 'COMMUNITY', bn: 'সম্প্রদায়' },
  homeNews3Title: { en: 'Women-led distribution networks ensure equitable relief in Netrokona', bn: 'নেত্রকোনায় নারী পরিচালিত নেটওয়ার্কের মাধ্যমে সুষম ত্রাণ বিতরণ নিশ্চিত' },
  homeResilienceCat: { en: 'RESILIENCE', bn: 'পুনর্বাসন' },
  homeNews4Title: { en: 'Local leaders coordinate post-flood recovery in Kurigram char areas', bn: 'কুড়িগ্রামের চরাঞ্চলে বন্যা পরবর্তী পুনর্বাসনে স্থানীয় নেতৃবৃন্দের সমন্বয়' },
  homeHowHelpTag: { en: 'There are many ways to help flood-affected families', bn: 'বন্যা দুর্গতদের পাশে দাঁড়ানোর নানান উপায় রয়েছে' },
  homeHowHelpTitle: { en: 'How You Can Help', bn: 'আপনি যেভাবে সাহায্য করতে পারেন' },
  homeHowHelpDesc: { en: 'Support rescue logistics, deliver relief supplies, and help families reach safe shelter through the most urgent response channels.', bn: 'জরুরি উদ্ধার কার্যক্রম, ত্রাণ সহায়তা পৌঁছে দেওয়া এবং পরিবারগুলোকে নিরাপদ আশ্রয়ে পৌঁছাতে সহযোগিতা করুন।' },
  homeReliefTransport: { en: 'Relief Transport', bn: 'ত্রাণ পরিবহন' },
  homeReliefTransportTitle: { en: 'Supplies moving into flooded communities', bn: 'প্লাবিত এলাকায় ত্রাণ সামগ্রী পৌঁছে দেওয়া হচ্ছে' },
  homeCommunitySupport: { en: 'Community Support', bn: 'কমিউনিটি সহযোগিতা' },
  homeCommunitySupportTitle: { en: 'Local responders guiding families to safety', bn: 'স্থানীয় স্বেচ্ছাসেবকদের সহায়তায় পরিবারগুলোকে নিরাপদ আশ্রয়ে পৌঁছানো' },
  homeLatestUpdates: { en: 'Latest Situation Updates', bn: 'সর্বশেষ পরিস্থিতি ও আপডেট' },
  homeAllAlerts: { en: 'All Alerts', bn: 'সকল সতর্কতা' },
  homeGovtVerified: { en: 'Government Verified', bn: 'সরকারিভাবে যাচাইকৃত' },
  homeTrackYourRequest: { en: 'Track Your Request', bn: 'আবেদনের অবস্থা দেখুন' },
  homeTrackDesc: { en: 'Enter your tracking ID to view rescue or relief status in real-time.', bn: 'রিয়েল-টাইমে উদ্ধার বা ত্রাণ আবেদনের অগ্রগতি দেখতে ট্র্যাকিং আইডি লিখুন।' },
  homeTrackSubmit: { en: 'Go', bn: 'অনুসন্ধান' },
  homeTrackErrorEmpty: { en: 'Please enter a valid tracking ID', bn: 'অনুগ্রহ করে একটি সঠিক ট্র্যাকিং আইডি লিখুন' },
  homeTrackErrorNotFound: { en: 'Request ID not found. Try SHY-2024-89211', bn: 'আইডি খুঁজে পাওয়া যায়নি। চেষ্টা করুন: SHY-2024-89211' },
  homeSubmittedFor: { en: 'Submitted for:', bn: 'আবেদনকৃত এলাকা:' },
  homeEmergencyHotlines: { en: 'Emergency Hotlines', bn: 'জরুরি হটলাইনসমূহ' },
  homeNationalEmergency: { en: 'National Emergency', bn: 'জাতীয় জরুরি সেবা' },
  homeFireService: { en: 'Fire Service & Civil Defence', bn: 'ফায়ার সার্ভিস ও সিভিল ডিফেন্স' },
  homeAmbulanceService: { en: 'Ambulance Service', bn: 'অ্যাম্বুলেন্স সার্ভিস' },
  homeAllContacts: { en: 'All Contacts →', bn: 'সকল যোগাযোগ →' },
  homeBottomVolunteerTitle: { en: 'Volunteer', bn: 'স্বেচ্ছাসেবক' },
  homeBottomVolunteerDesc: { en: 'Join field teams and help distribute relief to families in need across affected districts.', bn: 'মাঠপর্যায়ের দলের সাথে যুক্ত হয়ে ক্ষতিগ্রস্ত জেলাগুলোতে পরিবারগুলোর মাঝে ত্রাণ পৌঁছে দিন।' },
  homeJoinNow: { en: 'Join Now', bn: 'যুক্ত হোন' },
  homeBottomTransparencyTitle: { en: 'Transparency', bn: 'স্বচ্ছতা' },
  homeBottomTransparencyDesc: { en: 'Track how donated funds and materials are utilized with real-time audit logs and field reports.', bn: 'রিয়েল-টাইম অডিট লগ এবং ফিল্ড রিপোর্টের মাধ্যমে অনুদানের অর্থ ও উপকরণের সঠিক ব্যবহার পর্যবেক্ষণ করুন।' },
  homeViewReports: { en: 'View Reports', bn: 'প্রতিবেদন দেখুন' },
  homeBottomImpactTitle: { en: 'Our Impact', bn: 'আমাদের কার্যক্রমের প্রভাব' },
  homeBottomImpactDesc: { en: '5,000+ rescues coordinated and 50,000+ meals distributed in the past 14 days.', bn: 'গত ১৪ দিনে ৫,০০০+ উদ্ধার অভিযান এবং ৫০,০০০+ মানুষের মাঝে খাবার বিতরণ করা হয়েছে।' },
  homeImpactReport: { en: 'Impact Report', bn: 'ইমপ্যাক্ট রিপোর্ট' },
  // Get Help Page
  stepType: { en: 'Type', bn: 'ধরন' },
  stepHousehold: { en: 'Household', bn: 'পরিবার' },
  stepLocation: { en: 'Location', bn: 'অবস্থান' },
  stepContact: { en: 'Contact', bn: 'যোগাযোগ' },
  stepReview: { en: 'Review', bn: 'পর্যালোচনা' },
  getHelpSubtitle: { en: 'No account needed. Anonymous if preferred.', bn: 'অ্যাকাউন্টের প্রয়োজন নেই। চাইলে পরিচয় গোপন রাখতে পারেন।' },
  assistanceTypeRescue: { en: 'Rescue / Evacuation', bn: 'উদ্ধার / স্থানান্তর' },
  assistanceTypeShelter: { en: 'Shelter', bn: 'আশ্রয়' },
  assistanceTypeFood: { en: 'Food', bn: 'খাদ্য সহায়তা' },
  assistanceTypeWater: { en: 'Safe Water', bn: 'নিরাপদ পানি' },
  assistanceTypeMedicine: { en: 'Medicine / Medical Supply', bn: 'ওষুধ / চিকিৎসা সামগ্রী' },
  assistanceTypeMedicalEmergency: { en: 'Medical Emergency', bn: 'জরুরি চিকিৎসা' },
  assistanceTypeMaternal: { en: 'Maternal / Newborn Care', bn: 'মাতৃ ও নবজাতক সেবা' },
  assistanceTypeChildWelfare: { en: 'Child Welfare', bn: 'শিশু কল্যাণ' },
  assistanceTypeDisability: { en: 'Disability Assistance', bn: 'প্রতিবন্ধী সহায়তা' },
  assistanceTypeHygiene: { en: 'Hygiene Supplies', bn: 'স্বাস্থ্য সুরক্ষা সামগ্রী' },
  assistanceTypeMissingPerson: { en: 'Missing Person', bn: 'নিখোঁজ ব্যক্তি সন্ধান' },
  assistanceTypeEvacuation: { en: 'Evacuation Transport', bn: 'স্থানান্তর পরিবহন' },
  assistanceTypeOther: { en: 'Other / Multiple', bn: 'অন্যান্য / একাধিক' },
  priorityTag: { en: 'Priority', bn: 'জরুরি' },
  whatDoYouNeed: { en: 'What do you need?', bn: 'আপনার কী ধরণের সাহায্য প্রয়োজন?' },
  householdDetails: { en: 'Household Details', bn: 'পরিবারের বিবরণ' },
  totalPeopleHousehold: { en: 'Total Number of People in Household', bn: 'পরিবারে মোট সদস্য সংখ্যা' },
  childrenUnder12: { en: 'Children (Under 12)', bn: 'শিশু (১২ বছরের নিচে)' },
  elderly60: { en: 'Elderly (60+)', bn: 'বয়োজ্যেষ্ঠ (৬০+ বছর)' },
  pregnantWomen: { en: 'Pregnant Women', bn: 'গর্ভবতী নারী' },
  disabledSpecialCare: { en: 'Disabled / Special Care', bn: 'প্রতিবন্ধী / বিশেষ যত্ন প্রয়োজন' },
  yourLocation: { en: 'Your Location', bn: 'আপনার অবস্থান' },
  districtLabel: { en: 'District', bn: 'জেলা' },
  upazilaLabel: { en: 'Upazila', bn: 'উপজেলা' },
  unionWardLabel: { en: 'Union / Ward', bn: 'ইউনিয়ন / ওয়ার্ড' },
  fullAddressVillageLabel: { en: 'Full Address / Village', bn: 'গ্রাম / পূর্ণ ঠিকানা' },
  landmarkOptionalLabel: { en: 'Landmark (Optional, e.g., near high school)', bn: 'পরিচিত স্থান (ঐচ্ছিক, যেমন: স্কুলের কাছে)' },
  contactInformation: { en: 'Contact Information', bn: 'যোগাযোগের তথ্য' },
  yourNameLabel: { en: 'Your Name', bn: 'আপনার নাম' },
  mobilePhoneLabel: { en: 'Mobile Phone Number', bn: 'মোবাইল ফোন নম্বর' },
  altPhoneOptionalLabel: { en: 'Alternative Phone Number (Optional)', bn: 'বিকল্প ফোন নম্বর (ঐচ্ছিক)' },
  anonymousCheckboxLabel: { en: 'Keep my request anonymous to public', bn: 'জনসাধারণের কাছে আমার পরিচয় গোপন রাখুন' },
  reviewSubmitHeading: { en: 'Review & Submit', bn: 'যাচাই ও নিশ্চিতকরণ' },
  requestedServicesLabel: { en: 'Requested Services:', bn: 'আবেদনকৃত সেবাসমূহ:' },
  generalRelief: { en: 'General Relief', bn: 'সাধারণ ত্রাণ' },
  peopleLabel: { en: 'people', bn: 'জন' },
  childrenLabel: { en: 'children', bn: 'শিশু' },
  elderlyLabel: { en: 'elderly', bn: 'বয়োজ্যেষ্ঠ' },
  anonymousText: { en: 'Anonymous', bn: 'নাম প্রকাশে অনিচ্ছুক' },
  backBtn: { en: 'Back', bn: 'পেছনে' },
  nextBtn: { en: 'Next', bn: 'পরবর্তী' },
  submitAssistanceRequestBtn: { en: 'Submit Assistance Request', bn: 'সাহায্যের আবেদন জমা দিন' },
  assistanceRequestSubmitted: { en: 'Assistance Request Submitted!', bn: 'সাহায্যের আবেদন সফলভাবে জমা হয়েছে!' },
  requestRegisteredNotice: { en: 'Your request has been registered in the SHOHAY response network.', bn: 'সহায় রেসপন্স নেটওয়ার্কে আপনার আবেদনটি নিবন্ধিত হয়েছে।' },
  yourTrackingIdLabel: { en: 'YOUR TRACKING ID:', bn: 'আপনার ট্র্যাকিং আইডি:' },
  saveIdHint: { en: 'Save this ID to check rescue or relief status on the homepage.', bn: 'হোমপেজে উদ্ধার বা ত্রাণ আবেদনের অগ্রগতি দেখতে এই আইডিটি সংরক্ষণ করুন।' },
  returnToHomeBtn: { en: 'Return to Home', bn: 'হোমে ফিরে যান' },
  // Alerts Page
  activeLabel: { en: 'active', bn: 'সক্রিয়' },
  alertsSearchPlaceholder: { en: 'Search by area or keyword...', bn: 'এলাকা বা কীওয়ার্ড দিয়ে অনুসন্ধান করুন...' },
  filterAll: { en: 'All', bn: 'সকল' },
  sevCritical: { en: 'CRITICAL', bn: 'সংকটপূর্ণ' },
  sevHigh: { en: 'HIGH', bn: 'উচ্চ ঝুঁকি' },
  sevMedium: { en: 'MEDIUM', bn: 'মাঝারি' },
  sevLow: { en: 'LOW', bn: 'কম ঝুঁকি' },
  sevAllClear: { en: 'ALL CLEAR', bn: 'স্বাভাবিক' },
  noAlertsFound: { en: 'No flood alerts found matching your criteria.', bn: 'আপনার অনুসন্ধানের সাথে মিলে এমন কোনো বন্যা সতর্কতা পাওয়া যায়নি।' },
  // Shelters Page
  openSheltersLabel: { en: 'Open Shelters', bn: 'উন্মুক্ত আশ্রয়কেন্দ্র' },
  nearlyFullLabel: { en: 'Nearly Full', bn: 'প্রায় পূর্ণ' },
  freeSpacesLabel: { en: 'Free Spaces', bn: 'খালি স্থান' },
  filterSheltersHeading: { en: 'Filter Shelters', bn: 'ফিল্টার করুন' },
  statusLabel: { en: 'Status', bn: 'অবস্থা' },
  districtFilterLabel: { en: 'District', bn: 'জেলা' },
  mustHaveLabel: { en: 'Must have', bn: 'প্রয়োজনীয় সুবিধাসমূহ' },
  amenityDrinkingWater: { en: 'Drinking Water', bn: 'খাবার পানি' },
  amenityToilets: { en: 'Toilets', bn: 'টয়লেট' },
  amenityWomenToilets: { en: "Women's Toilets", bn: 'নারীদের টয়লেট' },
  amenityElectricity: { en: 'Electricity', bn: 'বিদ্যুৎ' },
  amenityGenerator: { en: 'Generator', bn: 'জেনারেটর' },
  amenityFood: { en: 'Food', bn: 'খাবার' },
  amenityMedicalSupport: { en: 'Medical Support', bn: 'চিকিৎসা সহায়তা' },
  statusOpen: { en: 'Open', bn: 'উন্মুক্ত' },
  statusNearlyFull: { en: 'Nearly Full', bn: 'প্রায় পূর্ণ' },
  statusFull: { en: 'Full', bn: 'পূর্ণ' },
  statusUnverified: { en: 'Unverified', bn: 'অযাচাইকৃত' },
  routeCaution: { en: 'Caution', bn: 'সতর্কতা' },
  routeBlocked: { en: 'Blocked', bn: 'বন্ধ' },
  routeOk: { en: 'Route OK', bn: 'সচল' },
  sheltersShown: { en: 'shelters shown', bn: 'টি আশ্রয়কেন্দ্র প্রদর্শিত' },
  // Campaigns Page
  campaignsTitle: { en: 'Relief Campaigns & Donations', bn: 'ত্রাণ ক্যাম্পেইন ও অনুদান' },
  campaignsSubtitle: { en: 'All campaigns are verified by SHOHAY before listing. Track fund usage transparently.', bn: 'তালিকভুক্তির পূর্বে সহায় কর্তৃক সকল ক্যাম্পেইন যাচাই করা হয়। অনুদানের সঠিক ব্যবহার স্বচ্ছভাবে পর্যবেক্ষণ করুন।' },
  activeCampaignsLabel: { en: 'Active Campaigns', bn: 'সক্রিয় ক্যাম্পেইন' },
  householdsReachedLabel: { en: 'Households Reached', bn: 'সাহায্যপ্রাপ্ত পরিবার' },
  totalRaisedBDTLabel: { en: 'Total Raised (BDT)', bn: 'মোট সংগৃহীত অনুদান (টাকা)' },
  ofTarget: { en: 'of', bn: 'এর মধ্যে' },
  householdsReachedText: { en: 'households reached', bn: 'টি পরিবারে সাহায্য পৌঁছেছে' },
  viewDonateBtn: { en: 'View & Donate →', bn: 'বিস্তারিত ও অনুদান →' },
  // Contacts Page
  contactsWarning: { en: 'Please verify all contact numbers with official sources before use in an emergency.', bn: 'জরুরি পরিস্থিতিতে ব্যবহারের পূর্বে অনুগ্রহ করে সরকারি ও প্রাতিষ্ঠানিক উৎস থেকে নম্বরগুলো যাচাই করে নিন।' },
  nationalEmergencyNumbersHeading: { en: 'National Emergency Numbers', bn: 'জাতীয় জরুরি নম্বরসমূহ' },
  nationalEmergencyNumbersSub: { en: 'Available 24/7. Verify numbers from primary sources.', bn: '২৪/৭ সার্বক্ষণিক সেবা চালু। প্রাথমিক উৎস থেকে নম্বর যাচাই করুন।' },
  demoTag: { en: '(DEMO)', bn: '(ডেমো)' },
  catNationalEmergency: { en: 'National Emergency', bn: 'জাতীয় জরুরি সেবা' },
  catFireService: { en: 'Fire Service', bn: 'ফায়ার সার্ভিস' },
  catMedical: { en: 'Medical', bn: 'চিকিৎসা' },
  catDisasterManagement: { en: 'Disaster Management', bn: 'দুর্যোগ ব্যবস্থাপনা' },
  catDistrictControlRoom: { en: 'District Control Room', bn: 'জেলা নিয়ন্ত্রণ কক্ষ' },
  catProtection: { en: 'Protection', bn: 'নিরাপত্তা ও সুরক্ষা' },
  catPlatformHotline: { en: 'Platform Hotline', bn: 'সহায় প্ল্যাটফর্ম হটলাইন' },
  catRescue: { en: 'Rescue', bn: 'উদ্ধার সেবা' },
  catHospital: { en: 'Hospital', bn: 'হাসপাতাল' },
  allDistricts: { en: 'All Districts', bn: 'সকল জেলা' },
  tollFree: { en: 'Toll Free', bn: 'টোল ফ্রি' },
  verified: { en: 'Verified', bn: 'যাচাইকৃত' },
  lastVerified: { en: 'Last verified:', bn: 'সর্বশেষ যাচাই:' },
  callBtn: { en: 'Call', bn: 'কল করুন' },
  copyPhoneNumber: { en: 'Copy Phone Number', bn: 'ফোন নম্বর কপি করুন' },
  bookmark: { en: 'Bookmark', bn: 'সংরক্ষণ' },
  // SignIn Page
  hadithQuote: { en: '“And whoever helps his brother (in need), Allah will be helping him; and whoever helps a believer to be free of a grievance, Allah will remove one of his grievances on the Day of Resurrection.”', bn: '“যে ব্যক্তি তার কোনো মুসলিম ভাইয়ের বিপদ দূর করবে, আল্লাহ তায়ালা কিয়ামতের দিন তার বিপদ দূর করবেন; আর যে ব্যক্তি কোনো মুসলিমের গোপনীয়তা রক্ষা করবে, আল্লাহ দুনিয়া ও আখিরাতে তার গোপনীয়তা রক্ষা করবেন।”' },
  hadithCitation: { en: '(Sahih Muslim 2699)', bn: '(সহীহ মুসলিম ২৬৯৯)' },
  peopleHelped: { en: 'People helped', bn: 'সাহায্যপ্রাপ্ত মানুষ' },
  specialShelters: { en: 'Special shelters', bn: 'বিশেষ আশ্রয়কেন্দ্র' },
  partnerOrgs: { en: 'Partner orgs', bn: 'সহযোগী সংস্থা' },
  specialOps: { en: 'Special ops', bn: 'বিশেষ অভিযান' },
  fieldworkerRegistration: { en: 'Fieldworker Registration', bn: 'মাঠকর্মী নিবন্ধন' },
  publicRegistration: { en: 'Public Registration', bn: 'নাগরিক নিবন্ধন' },
  fieldworkerSub: { en: 'Fieldworker credentials and personal verification', bn: 'মাঠকর্মীর তথ্যাদি ও ব্যক্তিগত যাচাইকরণ' },
  publicSub: { en: 'Minimal, fast registration for community volunteers', bn: 'কমিউনিটি স্বেচ্ছাসেবকদের জন্য দ্রুত নিবন্ধন' },
  publicAccessTab: { en: 'PUBLIC ACCESS', bn: 'সাধারণ নাগরিক' },
  fieldWorkerTab: { en: 'FIELD WORKER', bn: 'মাঠকর্মী' },
  createAccount: { en: 'Create Account', bn: 'নতুন অ্যাকাউন্ট তৈরি' },
  emailAddressLabel: { en: 'EMAIL ADDRESS', bn: 'ইমেইল ঠিকানা' },
  signingInBtn: { en: 'Signing In...', bn: 'লগইন হচ্ছে...' },
  orDivider: { en: 'or', bn: 'অথবা' },
  signInWithOtpBtn: { en: 'Sign In with Email OTP', bn: 'ইমেইল ওটিপি দিয়ে সাইন ইন' },
  otpDisclaimerText: { en: 'Registered accounts log in directly without waiting for OTP.', bn: 'নিবন্ধিত ব্যবহারকারীরা ওটিপির জন্য অপেক্ষা না করে সরাসরি লগইন করতে পারবেন।' },
  signInViaResendOtp: { en: 'SIGN IN VIA RESEND OTP', bn: 'ইমেইল ওটিপি মাধ্যমে সাইন ইন' },
  directLoginBtn: { en: 'Direct Login', bn: 'সরাসরি লগইন' },
  confirmEmailLabel: { en: 'CONFIRM EMAIL', bn: 'ইমেইল নিশ্চিত করুন' },
  dispatchingBtn: { en: 'Dispatching...', bn: 'পাঠানো হচ্ছে...' },
  sendOtpViaResendBtn: { en: 'Send OTP via Resend', bn: 'ওটিপি কোড পাঠান' },
  enter6DigitOtp: { en: 'ENTER 6-DIGIT OTP CODE', bn: '৬-সংখ্যার ওটিপি কোডটি লিখুন' },
  verifyingBtn: { en: 'Verifying...', bn: 'যাচাই করা হচ্ছে...' },
  verifyAndEnterBtn: { en: 'Verify & Enter System', bn: 'যাচাই করুন ও প্রবেশ করুন' },
  emailVerifiedViaResend: { en: 'EMAIL ADDRESS (VERIFIED VIA RESEND)', bn: 'ইমেইল ঠিকানা (যাচাইকরণ প্রয়োজন)' },
  sendingBtn: { en: 'Sending...', bn: 'পাঠানো হচ্ছে...' },
  sendVerificationOtpBtn: { en: 'Send Verification OTP', bn: 'যাচাইকরণ ওটিপি পাঠান' },
  otpWillBeSentNotice: { en: 'A 6-digit security code will be sent to your email via Resend.', bn: 'আপনার ইমেইলে একটি ৬-সংখ্যার নিরাপত্তা কোড পাঠানো হবে।' },
  enterCodeSentTo: { en: 'ENTER 6-DIGIT CODE SENT TO', bn: 'কোডটি লিখুন যা পাঠানো হয়েছে:' },
  editBtn: { en: 'Edit', bn: 'পরিবর্তন' },
  verifyAndContinueProfile: { en: 'Verify & Continue Profile', bn: 'যাচাই করুন ও প্রোফাইল পূরণ করুন' },
  emailVerifiedBadge: { en: 'Email Verified', bn: 'ইমেইল যাচাইকৃত' },
  firstNameLabel: { en: 'FIRST NAME *', bn: 'নামের প্রথম অংশ *' },
  lastNameLabel: { en: 'LAST NAME *', bn: 'নামের শেষ অংশ *' },
  genderLabel: { en: 'GENDER', bn: 'লিঙ্গ' },
  phoneOptionalLabel: { en: 'PHONE (OPTIONAL)', bn: 'ফোন নম্বর (ঐচ্ছিক)' },
  chooseAvatarLabel: { en: 'CHOOSE AVATAR', bn: 'অবয়ব (অ্যাভাটার) নির্বাচন' },
  skillsLabel: { en: 'SKILLS (SELECT OR ADD CUSTOM)', bn: 'দক্ষতাসমূহ (নির্বাচন করুন বা যোগ করুন)' },
  selectedLabel: { en: 'selected', bn: 'টি নির্বাচিত' },
  typeCustomSkill: { en: 'Type custom skill...', bn: 'অন্য কোনো দক্ষতা লিখুন...' },
  addBtn: { en: 'Add', bn: 'যোগ করুন' },
  equipmentLabel: { en: 'EQUIPMENT (SELECT OR ADD CUSTOM)', bn: 'সরঞ্জাম ও উপকরণ (নির্বাচন করুন বা যোগ করুন)' },
  typeCustomEquipment: { en: 'Type custom equipment...', bn: 'অন্য কোনো সরঞ্জাম লিখুন...' },
  personalVerificationTitle: { en: 'Personal Verification & Certification', bn: 'ব্যক্তিগত পরিচয় ও সনদ যাচাইকরণ' },
  nidNumberLabel: { en: 'NID NUMBER *', bn: 'জাতীয় পরিচয়পত্র নম্বর (NID) *' },
  dobLabel: { en: 'DATE OF BIRTH *', bn: 'জন্ম তারিখ *' },
  addressLabel: { en: 'RESIDENTIAL / OPERATING ADDRESS *', bn: 'বর্তমান / কার্যক্রমের ঠিকানা *' },
  certLabel: { en: 'EXPERIENCE CERTIFICATE / CREDENTIALS', bn: 'অভিজ্ঞতা সনদ / পরিচয়পত্র' },
  creatingProfileBtn: { en: 'Creating Profile...', bn: 'প্রোফাইল তৈরি হচ্ছে...' },
  completeRegistrationBtn: { en: 'Complete Registration & Enter', bn: 'নিবন্ধন সম্পন্ন করুন ও প্রবেশ করুন' },
  dontHaveAccount: { en: "Don't have an account?", bn: 'অ্যাকাউন্ট নেই?' },
  createOne: { en: 'Create one', bn: 'নতুন অ্যাকাউন্ট খুলুন' },
  alreadyHaveAccount: { en: 'Already have an account?', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  // Volunteer Landing Page
  volHeroTitle: { en: 'Volunteer with SHOHAY', bn: 'সহায়ের সাথে স্বেচ্ছাসেবক হিসেবে যুক্ত হোন' },
  volHeroSub: { en: 'Join thousands of volunteers coordinating flood relief across Bangladesh.', bn: 'বাংলাদেশ জুড়ে বন্যা ত্রাণ সমন্বয়কারী হাজার হাজার স্বেচ্ছাসেবকের সাথে যোগ দিন।' },
  activeNowLabel: { en: 'Active Now', bn: 'বর্তমানে সক্রিয়' },
  avgResponseLabel: { en: 'Avg Response', bn: 'গড় সাড়া প্রদানের সময়' },
  fieldRescue: { en: 'Field Rescue', bn: 'মাঠপর্যায়ে উদ্ধার' },
  fieldRescueSub: { en: 'Boat rescue, evacuation', bn: 'নৌকায় উদ্ধার, স্থানান্তর' },
  distributionTitle: { en: 'Distribution', bn: 'ত্রাণ বিতরণ' },
  distributionSub: { en: 'Food, water, supplies', bn: 'খাদ্য, পানি ও প্রয়োজনীয় সামগ্রী' },
  medicalSupportTitle: { en: 'Medical Support', bn: 'চিকিৎসা সহায়তা' },
  medicalSupportSub: { en: 'First aid, health camps', bn: 'প্রাথমিক চিকিৎসা, স্বাস্থ্য ক্যাম্প' },
  coordinationTitle: { en: 'Coordination', bn: 'সমন্বয় ও তথ্য' },
  coordinationSub: { en: 'Logistics, admin, data', bn: 'লজিস্টিকস, প্রশাসনিক ও তথ্য ব্যবস্থাপনা' },
  registerAsVolunteerBtn: { en: 'Register as Volunteer', bn: 'স্বেচ্ছাসেবক হিসেবে নিবন্ধন করুন' },
  viewDashboardBtn: { en: 'View Dashboard', bn: 'ড্যাশবোর্ড দেখুন' },
  // Volunteer Register Page
  basicInfoStep: { en: 'Basic Info', bn: 'প্রাথমিক তথ্য' },
  skillsStep: { en: 'Skills', bn: 'দক্ষতা' },
  availabilityStep: { en: 'Availability', bn: 'সময় ও স্থান' },
  basicInformationTitle: { en: 'Basic Information', bn: 'প্রাথমিক তথ্য' },
  firstNamePlaceholder: { en: 'First Name', bn: 'নামের প্রথম অংশ' },
  lastNamePlaceholder: { en: 'Last Name', bn: 'নামের শেষ অংশ' },
  mobileNumberPlaceholder: { en: 'Mobile Number', bn: 'মোবাইল নম্বর' },
  emailOptionalPlaceholder: { en: 'Email (optional)', bn: 'ইমেইল (ঐচ্ছিক)' },
  skillsEquipmentTitle: { en: 'Skills & Equipment', bn: 'দক্ষতা ও সরঞ্জাম' },
  selectYourSkillsLabel: { en: 'Select Your Skills:', bn: 'আপনার দক্ষতাসমূহ নির্বাচন করুন:' },
  skillBoatRescue: { en: 'Boat Driving / Water Rescue', bn: 'নৌকা চালনা / উদ্ধার কাজ' },
  skillFoodDistribution: { en: 'Relief & Food Distribution', bn: 'ত্রাণ ও খাদ্য বিতরণ' },
  skillFirstAid: { en: 'First Aid / Medical Care', bn: 'প্রাথমিক চিকিৎসা সেবা' },
  skillShelterAdmin: { en: 'Shelter Management & Admin', bn: 'আশ্রয়কেন্দ্র ব্যবস্থাপনা' },
  doYouHaveEquipment: { en: 'Do you have personal equipment?', bn: 'আপনার কি নিজস্ব সরঞ্জাম রয়েছে?' },
  equipBoat: { en: 'I have access to an engine boat / speed boat', bn: 'আমার ইঞ্জিন বোট / স্পিডবোট ব্যবহারের সুযোগ আছে' },
  equipVehicle: { en: 'I have a vehicle (Truck / Pickup / Bike)', bn: 'আমার নিজস্ব যানবাহন আছে (ট্রাক / পিকআপ / বাইক)' },
  availabilityDistrictTitle: { en: 'Availability & Preferred District', bn: 'সময় ও পছন্দের জেলা' },
  primaryOperatingDistrict: { en: 'Primary Operating District', bn: 'কাজের প্রধান জেলা' },
  availabilityFieldLabel: { en: 'Availability', bn: 'সময় ও প্রাপ্যতা' },
  registrationComplete: { en: 'Registration Complete!', bn: 'নিবন্ধন সফলভাবে সম্পন্ন হয়েছে!' },
  welcomeVolunteerNotice: { en: 'Welcome to the SHOHAY volunteer network. Your ID is', bn: 'সহায় স্বেচ্ছাসেবক নেটওয়ার্কে আপনাকে স্বাগতম। আপনার আইডি:' },
  goToVolunteerDashboard: { en: 'Go to Volunteer Dashboard', bn: 'স্বেচ্ছাসেবক ড্যাশবোর্ডে যান' },
  pageNotFoundTitle: { en: '404 — Page Not Found', bn: '৪০৪ — পৃষ্ঠাটি পাওয়া যায়নি' },
  pageNotFoundDesc: { en: 'The page or resource you requested does not exist or has been relocated in the flood relief network.', bn: 'আপনার অনুরোধ করা পৃষ্ঠা বা তথ্যটি পাওয়া যায়নি অথবা বন্যা ত্রাণ নেটওয়ার্কে স্থানান্তরিত হয়েছে।' },
  pageNotFoundReturnHome: { en: 'Return to Homepage', bn: 'হোমপেজে ফিরে যান' },
  alertBannerCritical: { en: 'CRITICAL ALERT', bn: 'জরুরি সতর্কতা' },
  alertBannerEvacOrder: { en: 'Immediate Evacuation Order:', bn: 'অবিলম্বে সরিয়ে নেওয়ার নির্দেশ:' },
  alertBannerWarningDetail: { en: 'Extreme Flash Flood Warning — Sunamganj Sadar & Surrounding Areas.', bn: 'তীব্র আকস্মিক বন্যার সতর্কতা — সুনামগঞ্জ সদর ও পার্শ্ববর্তী এলাকা।' },
  alertBannerViewAlert: { en: 'View Alert', bn: 'সতর্কতা দেখুন' },
  alertBannerGetHelpNow: { en: 'GET HELP NOW', bn: 'এখনই সাহায্য নিন' },
  volJoinedLabel: { en: 'Joined:', bn: 'যুক্ত হয়েছেন:' },
  volAvailableStatus: { en: 'Available', bn: 'উপলব্ধ' },
  volTapToToggle: { en: 'Tap to toggle', bn: 'পরিবর্তন করতে চাপুন' },
  volHoursLabel: { en: 'Hours', bn: 'ঘণ্টা' },
  volTasksLabel: { en: 'Tasks', bn: 'দায়িত্ব' },
  volRatingLabel: { en: 'Rating', bn: 'রেটিং' },
  volCurrentAssignmentTitle: { en: 'Current Assignment', bn: 'বর্তমান দায়িত্ব' },
  volInProgressBadge: { en: 'In Progress', bn: 'চলমান' },
  volHoursRemaining: { en: 'hours remaining', bn: 'ঘণ্টা বাকি' },
  volTeamOf: { en: 'Team of', bn: 'সদস্য সংখ্যা' },
  volCheckedInActive: { en: 'Checked In ✓', bn: 'উপস্থিতি নিশ্চিত ✓' },
  volCheckInBtn: { en: 'Check In', bn: 'উপস্থিতি জানান' },
  volPauseBtn: { en: 'Pause', bn: 'বিরতি' },
  volReportBtn: { en: 'Report', bn: 'প্রতিবেদন' },
  volMySkillsTitle: { en: 'My Skills', bn: 'আমার দক্ষতাসমূহ' },
  volOpenAssignmentsTitle: { en: 'Open Assignments Near You', bn: 'আপনার নিকটস্থ উন্মুক্ত দায়িত্বসমূহ' },
  volAcceptBtn: { en: 'Accept', bn: 'গ্রহণ করুন' },
  volDeclineBtn: { en: 'Decline', bn: 'প্রত্যাখ্যান' },
  ccTitle: { en: 'Command Center', bn: 'কমান্ড সেন্টার' },
  ccSubtitle: { en: 'Administrator Dashboard — Shelter, Warehouse & Operations', bn: 'প্রশাসক ড্যাশবোর্ড — আশ্রয়কেন্দ্র, গুদাম ও কার্যক্রম' },
  ccOpsActive: { en: '■ Operations Active', bn: '■ কার্যক্রম সক্রিয়' },
  ccOpenRequests: { en: 'OPEN REQUESTS', bn: 'উন্মুক্ত অনুরোধ' },
  ccCriticalSub: { en: 'critical', bn: 'জরুরি' },
  ccActiveVolunteers: { en: 'ACTIVE VOLUNTEERS', bn: 'সক্রিয় স্বেচ্ছাসেবক' },
  ccRescueTeamsSub: { en: 'rescue teams', bn: 'উদ্ধারকারী দল' },
  ccShelterOccupancy: { en: 'SHELTER OCCUPANCY', bn: 'আশ্রয়কেন্দ্রের ধারণক্ষমতা' },
  ccNearlyFullSub: { en: 'nearly full', bn: 'প্রায় পূর্ণ' },
  ccHouseholdsReached: { en: 'HOUSEHOLDS REACHED', bn: 'সহায়তাপ্রাপ্ত পরিবার' },
  ccTodaySub: { en: 'today', bn: 'আজকে' },
  ccAwaitingVerification: { en: 'Awaiting Verification', bn: 'যাচাইয়ের অপেক্ষায়' },
  ccAvgVerifyTime: { en: 'Avg Verify Time', bn: 'গড় যাচাই সময়' },
  ccLowStockItems: { en: 'Low Stock Items', bn: 'স্বল্প মজুদের সামগ্রী' },
  ccOpenComplaints: { en: 'Open Complaints', bn: 'অমীমাংসিত অভিযোগ' },
  ccTabOverview: { en: 'Overview', bn: 'সারসংক্ষেপ' },
  ccTabRequests: { en: 'Requests', bn: 'অনুরোধসমূহ' },
  ccTabShelters: { en: 'Shelters', bn: 'আশ্রয়কেন্দ্র' },
  ccTabWarehouse: { en: 'Warehouse', bn: 'গুদাম' },
  ccTabVerifyQueue: { en: 'Verify Queue', bn: 'যাচাই কিউ' },
  ccRequestTrendTitle: { en: 'REQUEST TREND (7 DAYS)', bn: 'অনুরোধের গতিধারা (৭ দিন)' },
  ccLegendSubmitted: { en: 'Submitted', bn: 'জমা পড়েছে' },
  ccLegendResolved: { en: 'Resolved', bn: 'সমাধান হয়েছে' },
  ccShelterOccupancyByDistrict: { en: 'SHELTER OCCUPANCY BY DISTRICT', bn: 'জেলা অনুযায়ী আশ্রয়কেন্দ্রের উপস্থিতি' },
  ccDistrictsActiveTitle: { en: 'Districts Active', bn: 'সক্রিয় জেলাসমূহ' },
  ccPartnerOrgsTitle: { en: 'Partner Organizations', bn: 'সহযোগী সংস্থাসমূহ' },
  ccMoreSuffix: { en: 'more', bn: 'আরও' },
  ccActiveAlertsTitle: { en: 'Active Alerts', bn: 'সক্রিয় সতর্কবার্তা' },
  ccSeverityCritical: { en: 'Critical:', bn: 'সংকটাপন্ন:' },
  ccSeverityHigh: { en: 'High:', bn: 'উচ্চ:' },
  ccSeverityMed: { en: 'Med:', bn: 'মাঝারি:' },
  ccSeverityLow: { en: 'Low:', bn: 'নিম্ন:' },
  ccSeverityAllClear: { en: 'All Clear:', bn: 'স্বাভাবিক:' },
  warehouseTitle: { en: 'Warehouse & Inventory', bn: 'গুদাম ও মজুদ সামগ্রী' },
  warehouseSubtitle: { en: 'Live inventory across all registered warehouses', bn: 'সকল নিবন্ধিত গুদামের সরাসরি মজুদ তথ্য' },
  warehouseReceiveStock: { en: 'Receive Stock', bn: 'পণ্য গ্রহণ' },
  warehouseLowStockBannerTitle: { en: '3 Items Below Minimum Stock', bn: '৩টি পণ্য ন্যূনতম মজুদের নিচে রয়েছে' },
  warehouseLowStockBannerDesc: { en: 'Insulin (Rapid-acting), Menstrual Hygiene Kit, Baby Food (Formula)', bn: 'ইনসুলিন, স্যানিটারি ন্যাপকিন কিট, শিশুর ফর্মুলা' },
  warehouseExpiringBannerTitle: { en: '3 Items Expiring Within 60 Days', bn: '৩টি পণ্যের মেয়াদ ৬০ দিনের মধ্যে শেষ হবে' },
  warehouseExpiringBannerDesc: { en: 'Oral Saline (ORS), Insulin (Rapid-acting), Baby Food (Formula)', bn: 'খাবার স্যালাইন (ORS), ইনসুলিন, শিশুর ফর্মুলা' },
  warehouseTabInventory: { en: 'Inventory', bn: 'মজুদ' },
  warehouseTabMovements: { en: 'Movements', bn: 'স্থানান্তর' },
  whCatAll: { en: 'All', bn: 'সকল' },
  whCatFood: { en: 'Food', bn: 'খাদ্য' },
  whCatWater: { en: 'Water', bn: 'পানি' },
  whCatMedicine: { en: 'Medicine', bn: 'ঔষধ' },
  whCatHygiene: { en: 'Hygiene', bn: 'স্বাস্থ্যবিধি' },
  whCatRescueEquipment: { en: 'Rescue Equipment', bn: 'উদ্ধার সরঞ্জাম' },
  whCatShelter: { en: 'Shelter', bn: 'আশ্রয় সামগ্রী' },
  whThItem: { en: 'Item', bn: 'পণ্য' },
  whThCategory: { en: 'Category', bn: 'বিভাগ' },
  whThAvailable: { en: 'Available', bn: 'মজুদ আছে' },
  whThReserved: { en: 'Reserved', bn: 'সংরক্ষিত' },
  whThMinStock: { en: 'Min Stock', bn: 'ন্যূনতম মজুদ' },
  whThStatus: { en: 'Status', bn: 'অবস্থা' },
  whThExpiry: { en: 'Expiry', bn: 'মেয়াদ' },
  whThWarehouse: { en: 'Warehouse', bn: 'গুদাম' },
  whThLastCount: { en: 'Last Count', bn: 'সর্বশেষ গণনা' },
  // UAV Monitor
  uavTitle: { en: 'UAV Monitor', bn: 'ড্রোন মনিটর' },
  uavSubtitle: { en: 'Drone patrols and on-board detections of stranded people', bn: 'ড্রোন টহল এবং পানিবন্দী মানুষদের স্বয়ংক্রিয় শনাক্তকরণ' },
  uavLiveBadge: { en: 'live, updated', bn: 'সরাসরি, আপডেট:' },
  uavBackToCommandCenter: { en: '← Command Center', bn: '← কমান্ড সেন্টার' },
  uavRegisterDroneBtn: { en: 'Register Drone', bn: 'ড্রোন নিবন্ধন করুন' },
  uavDronesOnlineStat: { en: 'DRONES ONLINE', bn: 'সক্রিয় ড্রোন' },
  uavDronesOfflineSub: { en: 'Offline after 2 min without heartbeat', bn: '২ মিনিট যোগাযোগ না থাকলে অফলাইন' },
  uavNewDetectionsStat: { en: 'NEW DETECTIONS', bn: 'নতুন শনাক্তকরণ' },
  uavWaitingReviewSub: { en: 'Waiting for review', bn: 'পর্যালোচনার অপেক্ষায়' },
  uavRescueRequestsStat: { en: 'RESCUE REQUESTS', bn: 'উদ্ধার অনুরোধ' },
  uavSentToQueueSub: { en: 'Sent to the request queue', bn: 'অনুরোধ কিউতে পাঠানো হয়েছে' },
  uavRescuersLinkedStat: { en: 'RESCUERS LINKED', bn: 'সংযুক্ত উদ্ধারকারী' },
  uavVolunteersAlertedSub: { en: 'Volunteers receiving drone alerts', bn: 'ড্রোন সতর্কবার্তা প্রাপ্ত স্বেচ্ছাসেবক' },
  uavLiveFeedTitle: { en: 'Live Feed', bn: 'সরাসরি ভিডিও সম্প্রচার' },
  uavDemoPlaybackOption: { en: 'Demo playback (no drone selected)', bn: 'ডেমো প্লেব্যাক (কোনো ড্রোন নির্বাচিত নেই)' },
  uavChooseRecordedVideo: { en: 'Choose recorded video…', bn: 'রেকর্ড করা ভিডিও নির্বাচন করুন…' },
  uavDetectionsTitle: { en: 'Detections', bn: 'শনাক্তকরণসমূহ' },
  uavStatusAll: { en: 'All', bn: 'সকল' },
  uavStatusNew: { en: 'New', bn: 'নতুন' },
  uavStatusAcknowledged: { en: 'Acknowledged', bn: 'স্বীকৃত' },
  uavStatusRescueRequested: { en: 'Rescue Requested', bn: 'উদ্ধার অনুরোধকৃত' },
  uavStatusDismissed: { en: 'Dismissed', bn: 'বাতিলকৃত' },
  uavRiskLabel: { en: 'Risk', bn: 'ঝুঁকি' },
  uavRescuersNeededLabel: { en: 'Rescuers needed', bn: 'প্রয়োজনীয় উদ্ধারকারী' },
  uavAlreadyPresentLabel: { en: 'Already present', bn: 'উপস্থিত আছেন' },
  uavDispatchCountLabel: { en: 'Dispatch count', bn: 'প্রেরিত উদ্ধারকারী' },
  uavPersonLabel: { en: 'Person', bn: 'ব্যক্তি' },
  uavAnimalLabel: { en: 'Animal', bn: 'প্রাণী' },
  uavConfidenceLabel: { en: 'confidence', bn: 'নিশ্চয়তা' },
  uavCreateRescueReqBtn: { en: 'Create rescue request', bn: 'উদ্ধার অনুরোধ তৈরি করুন' },
  uavAcknowledgeBtn: { en: 'Acknowledge', bn: 'স্বীকার করুন' },
  uavFalseAlarmBtn: { en: 'False alarm', bn: 'ভুল সংকেত' },
  uavDronesPanelTitle: { en: 'Drones', bn: 'ড্রোনসমূহ' },
  uavRescuerAssignmentsTitle: { en: "Who gets each drone's alerts", bn: 'ড্রোন সতর্কবার্তা প্রাপক' },
  uavAssignBtn: { en: 'Assign', bn: 'যুক্ত করুন' },
  uavAuditLogTitle: { en: 'Audit log', bn: 'কার্যক্রমের বিবরণী' },
  uavRegisterModalTitle: { en: 'Register a Drone', bn: 'ড্রোন নিবন্ধন করুন' },
  uavNameLabel: { en: 'Name', bn: 'নাম' },
  uavRegIdLabel: { en: 'Registration ID (printed on the drone)', bn: 'নিবন্ধন আইডি (ড্রোনে মুদ্রিত)' },
  uavDistrictLabel: { en: 'District', bn: 'জেলা' },
  uavLiveUrlLabel: { en: 'Live video URL (optional)', bn: 'লাইভ ভিডিও লিংক (ঐচ্ছিক)' },
  uavCancelBtn: { en: 'Cancel', bn: 'বাতিল' },
  uavRegisterSubmitBtn: { en: 'Register', bn: 'নিবন্ধন করুন' },
  // Donation
  donateBackToCampaigns: { en: 'Back to Campaigns', bn: 'ক্যাম্পেইনে ফিরে যান' },
  donateSecuredBy: { en: 'Secured by SSLCommerz (Sandbox)', bn: 'SSLCommerz (Sandbox) দ্বারা সুরক্ষিত' },
  donateReliefCampaign: { en: 'Relief Campaign', bn: 'ত্রাণ ক্যাম্পেইন' },
  donateAmountLabel: { en: 'Donation amount', bn: 'অনুদান পরিমাণ' },
  donateChooseAmountTitle: { en: 'Choose Amount (BDT)', bn: 'পরিমাণ নির্বাচন করুন (টাকা)' },
  donateCustomAmountPlaceholder: { en: 'Custom amount', bn: 'অন্যান্য পরিমাণ' },
  donateYourDetailsTitle: { en: 'Your Details', bn: 'আপনার তথ্য' },
  donateFullNamePlaceholder: { en: 'Full name', bn: 'পূর্ণ নাম' },
  donateEmailPlaceholder: { en: 'Email address', bn: 'ইমেইল ঠিকানা' },
  donateMobilePlaceholder: { en: 'Mobile number', bn: 'মোবাইল নম্বর' },
  donateContinueToPayment: { en: 'Continue to Payment', bn: 'পেমেন্টে এগিয়ে যান' },
  donateSuccessTitle: { en: 'Thank you for your support', bn: 'আপনার সহযোগিতার জন্য ধন্যবাদ' },
  donateFailTitle: { en: 'Payment did not go through', bn: 'পেমেন্ট সম্পন্ন হয়নি' },
  donateCancelTitle: { en: 'Payment cancelled', bn: 'পেমেন্ট বাতিল করা হয়েছে' },
  donateTryAgain: { en: 'Try Again', bn: 'আবার চেষ্টা করুন' },
  // My Requests
  myReqTitle: { en: 'My Requests', bn: 'আমার অনুরোধসমূহ' },
  myReqSubtitle: { en: "Every assistance request you've submitted while signed in — no tracking ID needed.", bn: 'লগইন থাকা অবস্থায় আপনার জমা দেওয়া প্রতিটি অনুরোধ — ট্র্যাকিং আইডি ছাড়াই সহজে দেখুন।' },
  myReqNewBtn: { en: 'New Request', bn: 'নতুন অনুরোধ' },
  myReqEmpty: { en: "You haven't submitted any requests yet", bn: 'আপনি এখনও কোনো অনুরোধ জমা দেননি' },
  myReqRequestAssistance: { en: 'Request Assistance', bn: 'সাহায্যের আবেদন' },
  // About
  aboutMissionTag: { en: 'Our Mission', bn: 'আমাদের লক্ষ্য' },
  aboutTitle: { en: 'Standing With Bangladesh in Times of Crisis', bn: 'সংকটের মুহূর্তে বাংলাদেশের পাশে' },
  aboutLead: { en: "Shohay (সহায়) is a flood-relief coordination platform connecting citizens who need help, volunteers who can respond, and district coordinators managing the response — built to make rescue and relief faster and more transparent during Bangladesh's flood season.", bn: 'সহায় একটি সমন্বিত বন্যা ত্রাণ প্ল্যাটফর্ম যা সাহায্যপ্রার্থী নাগরিক, মাঠপর্যায়ের স্বেচ্ছাসেবক এবং জেলা সমন্বয়কারীদের সরাসরি সংযুক্ত করে তাৎক্ষণিক সাড়া নিশ্চিত করে।' },
  aboutWhatWeDoTitle: { en: 'What we do', bn: 'আমরা কী করি' },
  aboutWhoItsForTitle: { en: "Who it's for", bn: 'কাদের জন্য' },
  aboutBuiltForTrustTitle: { en: 'Built for trust', bn: 'বিশ্বস্ততা ও স্বচ্ছতা' },
  aboutGrowingEffortTitle: { en: 'A growing effort', bn: 'আমাদের প্রচেষ্টা' },
  aboutWantToHelpTitle: { en: 'Want to help?', bn: 'সহযোগিতা করতে চান?' },
  aboutWantToHelpSub: { en: 'Join as a field volunteer, or support a verified relief campaign.', bn: 'স্বেচ্ছাসেবক হিসেবে যুক্ত হোন অথবা যাচাইকৃত ত্রাণ তহবিলে অনুদান দিন।' },
  aboutBecomeVolunteerBtn: { en: 'Become a Volunteer', bn: 'স্বেচ্ছাসেবক হোন' },
  aboutViewCampaignsBtn: { en: 'View Campaigns', bn: 'ক্যাম্পেইন দেখুন' },
  // News
  newsTitle: { en: 'News and Stories', bn: 'সংবাদ ও মাঠপর্যায়ের প্রতিবেদন' },
  newsSubtitle: { en: "Field reports from across Shohay's flood response.", bn: 'সহায়ের বন্যা ত্রাণ কার্যক্রমের মাঠপর্যায়ের খবরাখবর।' },
  newsReadMore: { en: 'Read More', bn: 'বিস্তারিত পড়ুন' },
  newsStoryNotFound: { en: 'Story not found', bn: 'প্রতিবেদনটি পাওয়া যায়নি' },
  newsBackToNews: { en: 'Back to News and Stories', bn: 'সকল সংবাদে ফিরে যান' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'bn' : 'en'));
  };

  const t = (key: string): string => {
    return DICTIONARY[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
